language: node_js
node_js:
  - "8"
  - "stable"

services:
  - redis-server

install:
  - yarn install --pure-lockfile

script:
  - node node_modules/.bin/jest --coverage --bail --noStackTrace --maxWorkers=1 --forceExit

